var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba="./this.program",ca=(a,b)=>{throw b;},da="object"==typeof window,h="function"==typeof importScripts,m="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,t="",ea,u,fa;
if(m){var fs=require("fs"),ha=require("path");t=h?ha.dirname(t)+"/":__dirname+"/";ea=(a,b)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};fa=a=>{a=ea(a,!0);a.buffer||(a=new Uint8Array(a));return a};u=(a,b,c,d=!0)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,g)=>{e?c(e):b(d?g.buffer:g)})};!f.thisProgram&&1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&
(module.exports=f);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof ia||a.context instanceof ia))throw a;});if(15>process.versions.node.split(".")[0])process.on("unhandledRejection",a=>{throw a;});ca=(a,b)=>{process.exitCode=a;throw b;};f.inspect=()=>"[Emscripten Module object]"}else if(da||h)h?t=self.location.href:"undefined"!=typeof document&&document.currentScript&&(t=document.currentScript.src),t=0!==t.indexOf("blob:")?t.substr(0,t.replace(/[?#].*/,"").lastIndexOf("/")+1):"",
ea=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},h&&(fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),u=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ja=f.print||console.log.bind(console),v=f.printErr||console.error.bind(console);
Object.assign(f,aa);aa=null;f.thisProgram&&(ba=f.thisProgram);f.quit&&(ca=f.quit);var w;f.wasmBinary&&(w=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&y("no native wasm support detected");var ka,la=!1,z,A,ma,C,D,na,oa=[],pa=[],qa=[];function ra(){var a=f.preRun.shift();oa.unshift(a)}var E=0,sa=null,F=null;function y(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";v(a);la=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}
function ta(a){return a.startsWith("data:application/octet-stream;base64,")}var G;G="index.wasm";if(!ta(G)){var ua=G;G=f.locateFile?f.locateFile(ua,t):t+ua}function va(a){try{if(a==G&&w)return new Uint8Array(w);if(fa)return fa(a);throw"both async and sync fetching of the wasm failed";}catch(b){y(b)}}
function wa(a){if(!w&&(da||h)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>va(a));if(u)return new Promise((b,c)=>{u(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>va(a))}function xa(a,b,c){return wa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{v("failed to asynchronously prepare wasm: "+d);y(d)})}
function ya(a,b){var c=G;w||"function"!=typeof WebAssembly.instantiateStreaming||ta(c)||c.startsWith("file://")||m||"function"!=typeof fetch?xa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){v("wasm streaming compile failed: "+e);v("falling back to ArrayBuffer instantiation");return xa(c,a,b)}))}var I,za;function ia(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
function Aa(a){for(;0<a.length;)a.shift()(f)}
var Ba=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},J=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ba(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ca=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Ea=a=>{if("/"===
a)return"/";a=J(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function Fa(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(m)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}y("initRandomDevice")}function Ga(a){return(Ga=Fa())(a)}
function Ha(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ba(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}function Ia(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}
function Ja(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var n=a.charCodeAt(++g);l=65536+((l&1023)<<10)|n&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}var Ka="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function K(a,b){for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ka)return Ka.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|l:(e&7)<<18|g<<12|l<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c}var La=[];
function Ma(a,b){La[a]={input:[],output:[],A:b};Na(a,Oa)}
var Oa={open:function(a){var b=La[a.node.rdev];if(!b)throw new L(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.A.fsync(a.tty)},fsync:function(a){a.tty.A.fsync(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.A.N)throw new L(60);for(var e=0,g=0;g<d;g++){try{var l=a.tty.A.N(a.tty)}catch(n){throw new L(29);}if(void 0===l&&0===e)throw new L(6);if(null===l||void 0===l)break;e++;b[c+g]=l}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.A.G)throw new L(60);try{for(var e=
0;e<d;e++)a.tty.A.G(a.tty,b[c+e])}catch(g){throw new L(29);}d&&(a.node.timestamp=Date.now());return e}},Pa={N:function(a){if(!a.input.length){var b=null;if(m){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==
b&&(b+="\n"));if(!b)return null;c=Array(Ia(b)+1);b=Ja(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},G:function(a,b){null===b||10===b?(ja(K(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(ja(K(a.output,0)),a.output=[])}},Qa={G:function(a,b){null===b||10===b?(v(K(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(v(K(a.output,0)),a.output=[])}},M={l:null,s:function(){return M.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(63);M.l||(M.l={dir:{node:{u:M.h.u,m:M.h.m,lookup:M.h.lookup,C:M.h.C,rename:M.h.rename,unlink:M.h.unlink,rmdir:M.h.rmdir,readdir:M.h.readdir,symlink:M.h.symlink},stream:{v:M.i.v}},file:{node:{u:M.h.u,m:M.h.m},stream:{v:M.i.v,read:M.i.read,write:M.i.write,I:M.i.I,O:M.i.O,R:M.i.R}},link:{node:{u:M.h.u,m:M.h.m,readlink:M.h.readlink},stream:{}},J:{node:{u:M.h.u,m:M.h.m},stream:Ra}});c=Sa(a,b,c,d);16384===(c.mode&
61440)?(c.h=M.l.dir.node,c.i=M.l.dir.stream,c.g={}):32768===(c.mode&61440)?(c.h=M.l.file.node,c.i=M.l.file.stream,c.j=0,c.g=null):40960===(c.mode&61440)?(c.h=M.l.link.node,c.i=M.l.link.stream):8192===(c.mode&61440)&&(c.h=M.l.J.node,c.i=M.l.J.stream);c.timestamp=Date.now();a&&(a.g[b]=c,a.timestamp=c.timestamp);return c},$:function(a){return a.g?a.g.subarray?a.g.subarray(0,a.j):new Uint8Array(a.g):new Uint8Array(0)},K:function(a,b){var c=a.g?a.g.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>
0),0!=c&&(b=Math.max(b,256)),c=a.g,a.g=new Uint8Array(b),0<a.j&&a.g.set(c.subarray(0,a.j),0))},W:function(a,b){if(a.j!=b)if(0==b)a.g=null,a.j=0;else{var c=a.g;a.g=new Uint8Array(b);c&&a.g.set(c.subarray(0,Math.min(b,a.j)));a.j=b}},h:{u:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.j:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);
b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.S=4096;b.blocks=Math.ceil(b.size/b.S);return b},m:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&M.W(a,b.size)},lookup:function(){throw Ta[44];},C:function(a,b,c,d){return M.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Ua(b,c)}catch(g){}if(d)for(var e in d.g)throw new L(55);}delete a.parent.g[a.name];a.parent.timestamp=Date.now();a.name=
c;b.g[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.g[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=Ua(a,b),d;for(d in c.g)throw new L(55);delete a.g[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.g)a.g.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(28);return a.link}},i:{read:function(a,b,c,d,e){var g=a.node.g;
if(e>=a.node.j)return 0;a=Math.min(a.node.j-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.g||a.g.subarray)){if(g)return a.g=b.subarray(c,c+d),a.j=d;if(0===a.j&&0===e)return a.g=b.slice(c,c+d),a.j=d;if(e+d<=a.j)return a.g.set(b.subarray(c,c+d),e),d}M.K(a,e+d);if(a.g.subarray&&b.subarray)a.g.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.g[e+g]=b[c+g];a.j=
Math.max(a.j,e+d);return d},v:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.j);if(0>b)throw new L(28);return b},I:function(a,b,c){M.K(a.node,b+c);a.node.j=Math.max(a.node.j,b+c)},O:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(43);a=a.node.g;if(e&2||a.buffer!==z.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;y();b=void 0;if(!b)throw new L(48);z.set(a,b)}else c=!1,b=a.byteOffset;return{ba:b,
Z:c}},R:function(a,b,c,d){M.i.write(a,b,0,d,c,!1);return 0}}};function Va(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
var Wa=null,Xa={},N=[],Ya=1,O=null,Za=!0,L=null,Ta={},P=(a,b={})=>{a=Ha(a);if(!a)return{path:"",node:null};b=Object.assign({M:!0,H:0},b);if(8<b.H)throw new L(32);a=a.split("/").filter(l=>!!l);for(var c=Wa,d="/",e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;c=Ua(c,a[e]);d=J(d+"/"+a[e]);c.D&&(!g||g&&b.M)&&(c=c.D.root);if(!g||b.L)for(g=0;40960===(c.mode&61440);)if(c=$a(d),d=Ha(Ca(d),c),c=P(d,{H:b.H+1}).node,40<g++)throw new L(32);}return{path:d,node:c}},ab=a=>{for(var b;;){if(a===a.parent)return a=
a.s.P,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},bb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%O.length},Ua=(a,b)=>{var c;if(c=(c=cb(a,"x"))?c:a.h.lookup?0:2)throw new L(c,a);for(c=O[bb(a.id,b)];c;c=c.V){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.h.lookup(a,b)},Sa=(a,b,c,d)=>{a=new db(a,b,c,d);b=bb(a.parent.id,a.name);a.V=O[b];return O[b]=a},eb=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},cb=
(a,b)=>{if(Za)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},fb=(a,b)=>{try{return Ua(a,b),20}catch(c){}return cb(a,"wx")},gb=()=>{for(var a=0;4096>=a;a++)if(!N[a])return a;throw new L(33);},hb=(a,b=-1)=>{Q||(Q=function(){this.B={}},Q.prototype={},Object.defineProperties(Q.prototype,{object:{get:function(){return this.node},set:function(c){this.node=c}},flags:{get:function(){return this.B.flags},set:function(c){this.B.flags=
c}},position:{get:function(){return this.B.position},set:function(c){this.B.position=c}}}));a=Object.assign(new Q,a);-1==b&&(b=gb());a.fd=b;return N[b]=a},Ra={open:a=>{a.i=Xa[a.node.rdev].i;a.i.open&&a.i.open(a)},v:()=>{throw new L(70);}},Na=(a,b)=>{Xa[a]={i:b}},ib=(a,b)=>{var c="/"===b,d=!b;if(c&&Wa)throw new L(10);if(!c&&!d){var e=P(b,{M:!1});b=e.path;e=e.node;if(e.D)throw new L(10);if(16384!==(e.mode&61440))throw new L(54);}b={type:a,aa:{},P:b,U:[]};a=a.s(b);a.s=b;b.root=a;c?Wa=a:e&&(e.D=b,e.s&&
e.s.U.push(b))},R=(a,b,c)=>{var d=P(a,{parent:!0}).node;a=Ea(a);if(!a||"."===a||".."===a)throw new L(28);var e=fb(d,a);if(e)throw new L(e);if(!d.h.C)throw new L(63);return d.h.C(d,a,b,c)},jb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);R(a,b|8192,c)},kb=(a,b)=>{if(!Ha(a))throw new L(44);var c=P(b,{parent:!0}).node;if(!c)throw new L(44);b=Ea(b);var d=fb(c,b);if(d)throw new L(d);if(!c.h.symlink)throw new L(63);c.h.symlink(c,b,a)},$a=a=>{a=P(a).node;if(!a)throw new L(44);if(!a.h.readlink)throw new L(28);
return Ha(ab(a.parent),a.h.readlink(a))},mb=(a,b,c)=>{if(""===a)throw new L(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=J(a);try{e=P(a,{L:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&128)throw new L(20);}else e=R(a,c,0),d=!0;if(!e)throw new L(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==
(e.mode&61440))throw new L(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==eb(b)||b&512)?31:cb(e,eb(b)):44))throw new L(c);if(b&512&&!d){c=e;c="string"==typeof c?P(c,{L:!0}).node:c;if(!c.h.m)throw new L(63);if(16384===(c.mode&61440))throw new L(31);if(32768!==(c.mode&61440))throw new L(28);if(d=cb(c,"w"))throw new L(d);c.h.m(c,{size:0,timestamp:Date.now()})}b&=-131713;e=hb({node:e,path:ab(e),flags:b,seekable:!0,position:0,i:e.i,Y:[],error:!1});e.i.open&&e.i.open(e);!f.logReadFiles||
b&1||(lb||(lb={}),a in lb||(lb[a]=1));return e},nb=(a,b,c)=>{if(null===a.fd)throw new L(8);if(!a.seekable||!a.i.v)throw new L(70);if(0!=c&&1!=c&&2!=c)throw new L(28);a.position=a.i.v(a,b,c);a.Y=[]},ob=()=>{L||(L=function(a,b){this.name="ErrnoError";this.node=b;this.X=function(c){this.o=c};this.X(a);this.message="FS error"},L.prototype=Error(),L.prototype.constructor=L,[44].forEach(a=>{Ta[a]=new L(a);Ta[a].stack="<generic error, no stack>"}))},pb,S=(a,b,c)=>{a=J("/dev/"+a);var d=Va(!!b,!!c);qb||(qb=
64);var e=qb++<<8|0;Na(e,{open:g=>{g.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(g,l,n,r)=>{for(var k=0,p=0;p<r;p++){try{var q=b()}catch(x){throw new L(29);}if(void 0===q&&0===k)throw new L(6);if(null===q||void 0===q)break;k++;l[n+p]=q}k&&(g.node.timestamp=Date.now());return k},write:(g,l,n,r)=>{for(var k=0;k<r;k++)try{c(l[n+k])}catch(p){throw new L(29);}r&&(g.node.timestamp=Date.now());return k}});jb(a,d,e)},qb,T={},Q,lb;
function rb(a,b){if("/"===b.charAt(0))return b;a=-100===a?"/":U(a).path;if(0==b.length)throw new L(44);return J(a+"/"+b)}var V=void 0;function Z(){V+=4;return C[V-4>>2]}function U(a){a=N[a];if(!a)throw new L(8);return a}m&&(global.performance=require("perf_hooks").performance);var sb={};
function tb(){if(!ub){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in sb)void 0===sb[b]?delete a[b]:a[b]=sb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);ub=c}return ub}var ub,vb=[];function db(a,b,c,d){a||(a=this);this.parent=a;this.s=a.s;this.D=null;this.id=Ya++;this.name=b;this.mode=c;this.h={};this.i={};this.rdev=d}
Object.defineProperties(db.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});ob();O=Array(4096);ib(M,"/");R("/tmp",16895,0);R("/home",16895,0);R("/home/web_user",16895,0);
(()=>{R("/dev",16895,0);Na(259,{read:()=>0,write:(d,e,g,l)=>l});jb("/dev/null",259);Ma(1280,Pa);Ma(1536,Qa);jb("/dev/tty",1280);jb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Ga(a).byteLength);return a[--b]};S("random",c);S("urandom",c);R("/dev/shm",16895,0);R("/dev/shm/tmp",16895,0)})();
(()=>{R("/proc",16895,0);var a=R("/proc/self",16895,0);R("/proc/self/fd",16895,0);ib({s:()=>{var b=Sa(a,"fd",16895,73);b.h={lookup:(c,d)=>{var e=N[+d];if(!e)throw new L(8);c={parent:null,s:{P:"fake"},h:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var yb={__syscall_fcntl64:function(a,b,c){V=c;try{var d=U(a);switch(b){case 0:var e=Z();return 0>e?-28:hb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Z(),d.flags|=e,0;case 5:return e=Z(),ma[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return C[wb()>>2]=28,-1;default:return-28}}catch(g){if("undefined"==typeof T||"ErrnoError"!==g.name)throw g;return-g.o}},__syscall_getcwd:function(a,b){try{if(0===b)return-28;var c=Ia("/")+1;if(b<c)return-68;Ja("/",A,a,
b);return c}catch(d){if("undefined"==typeof T||"ErrnoError"!==d.name)throw d;return-d.o}},__syscall_ioctl:function(a,b,c){V=c;try{var d=U(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=Z();return C[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=Z();if(!d.i.T)throw new L(59);return d.i.T(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==
typeof T||"ErrnoError"!==g.name)throw g;return-g.o}},__syscall_openat:function(a,b,c,d){V=d;try{b=b?K(A,b):"";b=rb(a,b);var e=d?Z():0;return mb(b,c,e).fd}catch(g){if("undefined"==typeof T||"ErrnoError"!==g.name)throw g;return-g.o}},__syscall_readlinkat:function(a,b,c,d){try{b=b?K(A,b):"";b=rb(a,b);if(0>=d)return-28;var e=$a(b),g=Math.min(d,Ia(e)),l=z[c+g];Ja(e,A,c,d+1);z[c+g]=l;return g}catch(n){if("undefined"==typeof T||"ErrnoError"!==n.name)throw n;return-n.o}},_emscripten_get_now_is_monotonic:function(){return!0},
_emscripten_throw_longjmp:function(){throw Infinity;},emscripten_date_now:function(){return Date.now()},emscripten_get_now:()=>performance.now(),emscripten_memcpy_big:function(a,b,c){A.copyWithin(a,b,b+c)},emscripten_resize_heap:function(){y("OOM")},environ_get:function(a,b){var c=0;tb().forEach(function(d,e){var g=b+c;e=D[a+4*e>>2]=g;for(g=0;g<d.length;++g)z[e++>>0]=d.charCodeAt(g);z[e>>0]=0;c+=d.length+1});return 0},environ_sizes_get:function(a,b){var c=tb();D[a>>2]=c.length;var d=0;c.forEach(function(e){d+=
e.length+1});D[b>>2]=d;return 0},exit:function(a){if(!noExitRuntime){if(f.onExit)f.onExit(a);la=!0}ca(a,new ia(a))},fd_close:function(a){try{var b=U(a);if(null===b.fd)throw new L(8);b.F&&(b.F=null);try{b.i.close&&b.i.close(b)}catch(c){throw c;}finally{N[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof T||"ErrnoError"!==c.name)throw c;return c.o}},fd_read:function(a,b,c,d){try{a:{var e=U(a);a=b;for(var g,l=b=0;l<c;l++){var n=D[a>>2],r=D[a+4>>2];a+=8;var k=e,p=n,q=r,x=g,Da=z;if(0>q||0>
x)throw new L(28);if(null===k.fd)throw new L(8);if(1===(k.flags&2097155))throw new L(8);if(16384===(k.node.mode&61440))throw new L(31);if(!k.i.read)throw new L(28);var W="undefined"!=typeof x;if(!W)x=k.position;else if(!k.seekable)throw new L(70);var X=k.i.read(k,Da,p,q,x);W||(k.position+=X);var B=X;if(0>B){var Y=-1;break a}b+=B;if(B<r)break;"undefined"!==typeof g&&(g+=B)}Y=b}D[d>>2]=Y;return 0}catch(H){if("undefined"==typeof T||"ErrnoError"!==H.name)throw H;return H.o}},fd_seek:function(a,b,c,d,
e){try{b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return 61;var g=U(a);nb(g,b,d);za=[g.position>>>0,(I=g.position,1<=+Math.abs(I)?0<I?+Math.floor(I/4294967296)>>>0:~~+Math.ceil((I-+(~~I>>>0))/4294967296)>>>0:0)];C[e>>2]=za[0];C[e+4>>2]=za[1];g.F&&0===b&&0===d&&(g.F=null);return 0}catch(l){if("undefined"==typeof T||"ErrnoError"!==l.name)throw l;return l.o}},fd_write:function(a,b,c,d){try{a:{var e=U(a);a=b;for(var g,l=b=0;l<c;l++){var n=D[a>>2],r=D[a+4>>2];a+=8;var k=e,p=n,q=r,
x=g,Da=z;if(0>q||0>x)throw new L(28);if(null===k.fd)throw new L(8);if(0===(k.flags&2097155))throw new L(8);if(16384===(k.node.mode&61440))throw new L(31);if(!k.i.write)throw new L(28);k.seekable&&k.flags&1024&&nb(k,0,2);var W="undefined"!=typeof x;if(!W)x=k.position;else if(!k.seekable)throw new L(70);var X=k.i.write(k,Da,p,q,x,void 0);W||(k.position+=X);var B=X;if(0>B){var Y=-1;break a}b+=B;"undefined"!==typeof g&&(g+=B)}Y=b}D[d>>2]=Y;return 0}catch(H){if("undefined"==typeof T||"ErrnoError"!==H.name)throw H;
return H.o}},invoke_vii:xb,system:function(a){if(m){if(!a)return 1;a=a?K(A,a):"";if(!a.length)return 0;a=require("child_process").ea(a,[],{da:!0,stdio:"inherit"});var b=(c,d)=>c<<8|d;return null===a.status?b(0,(c=>{switch(c){case "SIGHUP":return 1;case "SIGQUIT":return 3;case "SIGFPE":return 8;case "SIGKILL":return 9;case "SIGALRM":return 14;case "SIGTERM":return 15}return 2})(a.signal)):a.status<<8|0}if(!a)return 0;C[wb()>>2]=52;return-1}};
(function(){function a(c){c=c.exports;f.asm=c;ka=f.asm.memory;var d=ka.buffer;f.HEAP8=z=new Int8Array(d);f.HEAP16=ma=new Int16Array(d);f.HEAP32=C=new Int32Array(d);f.HEAPU8=A=new Uint8Array(d);f.HEAPU16=new Uint16Array(d);f.HEAPU32=D=new Uint32Array(d);f.HEAPF32=new Float32Array(d);f.HEAPF64=new Float64Array(d);na=f.asm.__indirect_function_table;pa.unshift(f.asm.__wasm_call_ctors);E--;f.monitorRunDependencies&&f.monitorRunDependencies(E);0==E&&(null!==sa&&(clearInterval(sa),sa=null),F&&(d=F,F=null,
d()));return c}var b={env:yb,wasi_snapshot_preview1:yb};E++;f.monitorRunDependencies&&f.monitorRunDependencies(E);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return v("Module.instantiateWasm callback failed with error: "+c),!1}ya(b,function(c){a(c.instance)});return{}})();f._run_tea=function(){return(f._run_tea=f.asm.run_tea).apply(null,arguments)};function wb(){return(wb=f.asm.__errno_location).apply(null,arguments)}
function zb(){return(zb=f.asm.setThrew).apply(null,arguments)}function Ab(){return(Ab=f.asm.stackSave).apply(null,arguments)}function Bb(){return(Bb=f.asm.stackRestore).apply(null,arguments)}function Cb(){return(Cb=f.asm.stackAlloc).apply(null,arguments)}f.dynCall_jiji=function(){return(f.dynCall_jiji=f.asm.dynCall_jiji).apply(null,arguments)};function xb(a,b,c){var d=Ab();try{var e=vb[a];e||(a>=vb.length&&(vb.length=a+1),vb[a]=e=na.get(a));e(b,c)}catch(g){Bb(d);if(g!==g+0)throw g;zb(1,0)}}
f.ccall=function(a,b,c,d){var e={string:k=>{var p=0;if(null!==k&&void 0!==k&&0!==k){p=Ia(k)+1;var q=Cb(p);Ja(k,A,q,p);p=q}return p},array:k=>{var p=Cb(k.length);z.set(k,p);return p}};a=f["_"+a];var g=[],l=0;if(d)for(var n=0;n<d.length;n++){var r=e[c[n]];r?(0===l&&(l=Ab()),g[n]=r(d[n])):g[n]=d[n]}c=a.apply(null,g);return c=function(k){0!==l&&Bb(l);return"string"===b?k?K(A,k):"":"boolean"===b?!!k:k}(c)};var Db;F=function Eb(){Db||Fb();Db||(F=Eb)};
function Fb(){function a(){if(!Db&&(Db=!0,f.calledRun=!0,!la)){f.noFSInit||pb||(pb=!0,ob(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?S("stdin",f.stdin):kb("/dev/tty","/dev/stdin"),f.stdout?S("stdout",null,f.stdout):kb("/dev/tty","/dev/stdout"),f.stderr?S("stderr",null,f.stderr):kb("/dev/tty1","/dev/stderr"),mb("/dev/stdin",0),mb("/dev/stdout",1),mb("/dev/stderr",1));Za=!1;Aa(pa);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=
[f.postRun]);f.postRun.length;){var b=f.postRun.shift();qa.unshift(b)}Aa(qa)}}if(!(0<E)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ra();Aa(oa);0<E||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();Fb();
